name: Unit Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Tests Coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Run lint
        run: npm run lint --fix
      - name: Run Unit Tests with Coverage
        run: npm run test:coverage
      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          COVERAGE=${COVERAGE//\"/}
          if [ $(echo "$COVERAGE < 70" | bc) -eq 1 ]; then
            echo "Coverage is below 70%: $COVERAGE%"
            exit 1
          fi
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
